# config.yml
loggable-entities:
  - ZOMBIE
  - COW
  - VILLAGER
  # Add other entities you want to log
max-log-files: 10
log-nametags: true
restart-check-enabled: true  # New option to enable or disable restart checks
