# config.yml
loggable-entities:
  - ALLAY
  - ARMADILLO
  - ARMOR_STAND
  - ARROW
  - AXOLOTL
  - BAT
  - BEE
  - BLAZE
  - BLOCK_DISPLAY
  - BOAT
  - BOGGED
  - BREEZE
  - BREEZE_WIND_CHARGE
  - CAMEL
  - CAT
  - CAVE_SPIDER
  - CHEST_BOAT
  - CHEST_MINECART
  - CHICKEN
  - COD
  - COMMAND_BLOCK_MINECART
  - COW
  - CREEPER
  - DOLPHIN
  - DONKEY
  - DROWNED
  - ELDER_GUARDIAN
  - ENDER_DRAGON
  - ENDERMAN
  - ENDERMITE
  - EVOKER
  - FOX
  - FROG
  - FURNACE_MINECART
  - GHAST
  - GIANT
  - GLOW_ITEM_FRAME
  - GLOW_SQUID
  - GOAT
  - GUARDIAN
  - HOGLIN
  - HOPPER_MINECART
  - HORSE
  - HUSK
  - ILLUSIONER
  - IRON_GOLEM
  - ITEM
  - ITEM_DISPLAY
  - ITEM_FRAME
  - LEASH_KNOT
  - LLAMA
  - MAGMA_CUBE
  - MINECART
  - MOOSHROOM
  - MULE
  - OCELOT
  - OMINOUS_ITEM_SPAWNER
  - PAINTING
  - PANDA
  - PARROT
  - PHANTOM
  - PIG
  - PIGLIN
  - PIGLIN_BRUTE
  - PILLAGER
  - PLAYER
  - POLAR_BEAR
  - PUFFERFISH
  - RABBIT
  - RAVAGER
  - SALMON
  - SHEEP
  - SHULKER
  - SILVERFISH
  - SKELETON
  - SKELETON_HORSE
  - SLIME
  - SNIFFER
  - SNOW_GOLEM
  - SPAWNER_MINECART
  - SPIDER
  - SQUID
  - STRAY
  - STRIDER
  - TADPOLE
  - TEXT_DISPLAY
  - TNT
  - TNT_MINECART
  - TRADER_LLAMA
  - TROPICAL_FISH
  - TURTLE
  - UNKNOWN
  - VEX
  - VILLAGER
  - VINDICATOR
  - WANDERING_TRADER
  - WARDEN
  - WIND_CHARGE
  - WITCH
  - WITHER
  - WITHER_SKELETON
  - WOLF
  - ZOGLIN
  - ZOMBIE
  - ZOMBIE_HORSE
  - ZOMBIE_VILLAGER
  - ZOMBIFIED_PIGLIN
  # Add or remove entities you want to log or not
max-log-files: 10
log-nametags: true
restart-check-enabled: true  # option to enable or disable restart checks
chunk-unload-logging: false # option to enable chuckunload logging (WARNING: it will spam the logs)
